//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string VERSION { get; set; }
        public string AUTHOR { get; set; }
        public string GENRE { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
